#ifndef BALSER_GIGECAMERA_GLOBAL_H
#define BALSER_GIGECAMERA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BALSER_GIGECAMERA_LIBRARY)
#  define BALSER_GIGECAMERASHARED_EXPORT Q_DECL_EXPORT
#else
#  define BALSER_GIGECAMERASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BALSER_GIGECAMERA_GLOBAL_H
